"""Model-neutral backend contracts and result/failure taxonomies.

T1 implements contracts and deterministic test doubles only. Vendor stubs in
``integrations.protocols`` remain documentation-only and are not implementations.
"""

from speaker_attribution_video.backends.capabilities import (
    Capabilities,
    Capability,
    require_capabilities,
)
from speaker_attribution_video.backends.contracts import (
    BACKEND_INPUT_SCHEMA_VERSION,
    BACKEND_OUTPUT_SCHEMA_VERSION,
    SYNTHETIC_URI_PREFIX,
    AlignmentBackend,
    AlignmentRequest,
    AttributionModelBackend,
    AttributionModelRequest,
    AudioBackend,
    AudioRequest,
    BackendIdentity,
    BackendResult,
    CancellationToken,
    DiarizationBackend,
    DiarizationRequest,
    GraphFragment,
    HealthResult,
    InvocationRecord,
    MediaRef,
    RequestContext,
    TelemetryBackend,
    TelemetryEvent,
    TelemetryExport,
    TelemetryRequest,
    TelemetryResult,
    TranscriptionBackend,
    TranscriptionRequest,
    VideoEvidenceBackend,
    VideoEvidenceRequest,
    fingerprint_config,
)
from speaker_attribution_video.backends.failures import (
    BackendError,
    FailureReason,
    ResultState,
    is_successful,
)

__all__ = [
    "BACKEND_INPUT_SCHEMA_VERSION",
    "BACKEND_OUTPUT_SCHEMA_VERSION",
    "SYNTHETIC_URI_PREFIX",
    "AlignmentBackend",
    "AlignmentRequest",
    "AttributionModelBackend",
    "AttributionModelRequest",
    "AudioBackend",
    "AudioRequest",
    "BackendError",
    "BackendIdentity",
    "BackendResult",
    "CancellationToken",
    "Capabilities",
    "Capability",
    "DiarizationBackend",
    "DiarizationRequest",
    "FailureReason",
    "GraphFragment",
    "HealthResult",
    "InvocationRecord",
    "MediaRef",
    "RequestContext",
    "ResultState",
    "TelemetryBackend",
    "TelemetryEvent",
    "TelemetryExport",
    "TelemetryRequest",
    "TelemetryResult",
    "TranscriptionBackend",
    "TranscriptionRequest",
    "VideoEvidenceBackend",
    "VideoEvidenceRequest",
    "fingerprint_config",
    "is_successful",
    "require_capabilities",
]
