"""MP1 schema versions for media-tool contracts."""

from __future__ import annotations

MEDIA_TOOL_SCHEMA_VERSION = "mp1.tool.v1"
MEDIA_TOOLCHAIN_SCHEMA_VERSION = "mp1.toolchain.v1"
SUBPROCESS_POLICY_VERSION = "mp1.subprocess.v1"
INSPECTION_SCHEMA_VERSION = "mp1.inspect.v1"
INSPECTION_INPUT_SCHEMA_VERSION = "mp1.inspect.input.v1"
NORMALIZATION_SCHEMA_VERSION = "mp1.normalize.v1"
NORMALIZATION_INPUT_SCHEMA_VERSION = "mp1.normalize.input.v1"

SUPPORTED_MEDIA_TOOL_SCHEMA_VERSIONS = frozenset({MEDIA_TOOL_SCHEMA_VERSION})
SUPPORTED_MEDIA_TOOLCHAIN_SCHEMA_VERSIONS = frozenset({MEDIA_TOOLCHAIN_SCHEMA_VERSION})
SUPPORTED_SUBPROCESS_POLICY_VERSIONS = frozenset({SUBPROCESS_POLICY_VERSION})
SUPPORTED_INSPECTION_SCHEMA_VERSIONS = frozenset({INSPECTION_SCHEMA_VERSION})
SUPPORTED_INSPECTION_INPUT_SCHEMA_VERSIONS = frozenset({INSPECTION_INPUT_SCHEMA_VERSION})
SUPPORTED_NORMALIZATION_SCHEMA_VERSIONS = frozenset({NORMALIZATION_SCHEMA_VERSION})
SUPPORTED_NORMALIZATION_INPUT_SCHEMA_VERSIONS = frozenset({NORMALIZATION_INPUT_SCHEMA_VERSION})
