"""Typed evidence and execution graph contracts (G1)."""

from __future__ import annotations

from speaker_attribution_video.graph.attribution import AdmissionIssue, admit_attribution, view_attribution
from speaker_attribution_video.graph.edges import (
    ACYCLIC_EDGE_TYPES,
    EdgeType,
    GraphEdge,
    make_edge,
)
from speaker_attribution_video.graph.enums import (
    DecisionState,
    DialogueKind,
    EvidenceSummary,
    FindingSeverity,
    ModelRole,
    NodeType,
    ProducerKind,
    ReasonCode,
    RepairCategory,
    ReviewOutcome,
    Sensitivity,
    TextMode,
)
from speaker_attribution_video.graph.errors import GraphContractError
from speaker_attribution_video.graph.ids import (
    EdgeId,
    JobId,
    MediaId,
    ModelInvocationId,
    NamespaceId,
    NodeId,
    ReviewerId,
)
from speaker_attribution_video.graph.nodes import (
    AttributionDecision,
    AudioArtifact,
    AudioEvidence,
    AudioSegment,
    CandidateIdentity,
    CorrectionAttempt,
    DiarizationTurn,
    DialogueEvidence,
    GraphNode,
    HumanReviewDecision,
    MediaArtifact,
    ModelInvocation,
    OutputArtifact,
    ProcessingStep,
    SpeakerCluster,
    TranscriptToken,
    TranscriptUtterance,
    ValidationFinding,
    VisualEvidence,
    make_node,
)
from speaker_attribution_video.graph.producer import Producer
from speaker_attribution_video.graph.text import SensitiveText
from speaker_attribution_video.graph.time import TimeSpan, format_utc, parse_utc
from speaker_attribution_video.graph.versions import (
    EDGE_SCHEMA_VERSION,
    GRAPH_SCHEMA_VERSION,
    ID_SCHEMA_VERSION,
    NODE_SCHEMA_VERSION,
)

__all__ = [
    "ACYCLIC_EDGE_TYPES",
    "AdmissionIssue",
    "AttributionDecision",
    "AudioArtifact",
    "AudioEvidence",
    "AudioSegment",
    "CandidateIdentity",
    "CorrectionAttempt",
    "DecisionState",
    "DiarizationTurn",
    "DialogueEvidence",
    "DialogueKind",
    "EDGE_SCHEMA_VERSION",
    "EdgeId",
    "EdgeType",
    "EvidenceSummary",
    "FindingSeverity",
    "GRAPH_SCHEMA_VERSION",
    "GraphContractError",
    "GraphEdge",
    "GraphNode",
    "HumanReviewDecision",
    "ID_SCHEMA_VERSION",
    "JobId",
    "MediaArtifact",
    "MediaId",
    "ModelInvocation",
    "ModelInvocationId",
    "ModelRole",
    "NODE_SCHEMA_VERSION",
    "NamespaceId",
    "NodeId",
    "NodeType",
    "OutputArtifact",
    "ProcessingStep",
    "Producer",
    "ProducerKind",
    "ReasonCode",
    "RepairCategory",
    "ReviewOutcome",
    "ReviewerId",
    "SensitiveText",
    "Sensitivity",
    "SpeakerCluster",
    "TextMode",
    "TimeSpan",
    "TranscriptToken",
    "TranscriptUtterance",
    "ValidationFinding",
    "VisualEvidence",
    "admit_attribution",
    "format_utc",
    "make_edge",
    "make_node",
    "parse_utc",
    "view_attribution",
]
